project:
  type: book
  output-dir: docs

execute:
  echo: true

book:
  title: "Analysis of the NYCT Express Bus Capacity"
  author:
    - Yuwen Sun (ys3748)
    - Shumail Sajjad (ss6972)
  repo-url: https://github.com/Jerryson520/MTA_NYCT.git
  date: today
  page-footer:
    right: |
      This book was built with <a href="https://quarto.org/">Quarto</a>.
  repo-actions: [edit, issue]
  chapters:
    - index.qmd
    - data.qmd
    - results.qmd
    - d3graph.qmd
    - conclusion.qmd

format:
  html:
    theme: cosmo
    code-fold: true


